### ISSUE TITLE
Include protocol.txt in the repository

### ISSUE THREAD

**Issue by dbohdan** [nascheme/scgi#1]
Could you add <https://python.ca/scgi/protocol.txt> to the repository?  If you do, it will be easy to link to a specific line or range of lines, for example, from a GitHub issue.

P.S.: Thank you so much for designing and implementing SCGI!  It is such a small and elegant protocol.  Tcl developers adopted it early and still favor it for writing web services.  The newish [Wapp web microframework](https://wapp.tcl-lang.org/home/doc/trunk/README.md) comes with first-class support for SCGI, and through Tcl SCGI has found its way into [Fossil SCM](https://fossil-scm.org/home/doc/trunk/www/server/any/scgi.md).

**Comment by nascheme** [comment]
Good idea.  Done.
